sources:
  - name: s1
    database: dev_Db
    schema: dev_Schema
    tables:
      - name: t_nation
      - name: t_customer
      - name: emp      
      - name: T_SSD

      - name: t_tickets_info      

